language: node_js
node_js:
  - "6.9.2"
dist: trusty
before_install:
  - git submodule update --init --recursive
addons:
  chrome: stable
install:
  - npm install
before_script:
  - npm install -g npm@3.10.9
  - npm install -g grunt-cli
script:
  - npm run test-ci
notifications:
  email:
    on_success: never
    on_failure: change
